services:
  - type: web
    name: skill-query-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: MONGO_URI
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
